/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author USER
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        playBackgroundMusic();
        jDesktopPane1.removeAll();
        DashBoard dash = new DashBoard();
        jDesktopPane1.add(dash).setVisible(true);
        Timer timer = new Timer(1000, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        // Call the curDateTime() method to update the label
        curDateTime();
    }
});

// Start the Timer
timer.start();

    }
    
    
    
    
   private void playBackgroundMusic() {
    try {
        // Load the audio file
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/Music/Microsoft Windows Vista Beta Shutdown Sound.wav"));

        // Create a clip to play the audio
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);

        // Play the audio once
        clip.start();
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    
    
       public void curDateTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd    HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lblDate.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        rSButtonHover2 = new rojerusan.RSButtonHover();
        rSButtonHover3 = new rojerusan.RSButtonHover();
        rSButtonHover4 = new rojerusan.RSButtonHover();
        rSButtonHover5 = new rojerusan.RSButtonHover();
        panel1 = new java.awt.Panel();
        rSPanelCircleImage1 = new rojerusan.RSPanelCircleImage();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        label2 = new java.awt.Label();
        jDesktopPane1 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonHover2.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rSButtonHover2.setForeground(new java.awt.Color(255, 204, 0));
        rSButtonHover2.setText("HOME");
        rSButtonHover2.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover2.setColorText(new java.awt.Color(255, 204, 0));
        rSButtonHover2.setColorTextHover(new java.awt.Color(255, 204, 0));
        rSButtonHover2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        panel2.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        rSButtonHover3.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rSButtonHover3.setForeground(new java.awt.Color(255, 204, 0));
        rSButtonHover3.setText("INVENTORY");
        rSButtonHover3.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover3.setColorText(new java.awt.Color(255, 204, 0));
        rSButtonHover3.setColorTextHover(new java.awt.Color(255, 204, 0));
        rSButtonHover3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        panel2.add(rSButtonHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        rSButtonHover4.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rSButtonHover4.setForeground(new java.awt.Color(255, 204, 0));
        rSButtonHover4.setText("MENU");
        rSButtonHover4.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover4.setColorText(new java.awt.Color(255, 204, 0));
        rSButtonHover4.setColorTextHover(new java.awt.Color(255, 204, 0));
        rSButtonHover4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        panel2.add(rSButtonHover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        rSButtonHover5.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rSButtonHover5.setForeground(new java.awt.Color(255, 204, 0));
        rSButtonHover5.setText("REPORT");
        rSButtonHover5.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover5.setColorText(new java.awt.Color(255, 204, 0));
        rSButtonHover5.setColorTextHover(new java.awt.Color(255, 204, 0));
        rSButtonHover5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });
        panel2.add(rSButtonHover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 220, 360));

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelCircleImage1.setBackground(new java.awt.Color(51, 51, 51));
        rSPanelCircleImage1.setColorBorde(new java.awt.Color(255, 204, 0));
        rSPanelCircleImage1.setColorFondo(new java.awt.Color(51, 51, 51));
        rSPanelCircleImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-contacts-125.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelCircleImage1Layout = new javax.swing.GroupLayout(rSPanelCircleImage1);
        rSPanelCircleImage1.setLayout(rSPanelCircleImage1Layout);
        rSPanelCircleImage1Layout.setHorizontalGroup(
            rSPanelCircleImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        rSPanelCircleImage1Layout.setVerticalGroup(
            rSPanelCircleImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        panel1.add(rSPanelCircleImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 101, 102));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonRectangle2.setForeground(new java.awt.Color(255, 204, 0));
        rSMaterialButtonRectangle2.setText("LOGOUT");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        panel1.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 40));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonRectangle3.setForeground(new java.awt.Color(255, 204, 0));
        rSMaterialButtonRectangle3.setText("ACCOUNT SETTINGS");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });
        panel1.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 40));

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 204, 0));
        label2.setText("ADMIN : 10001");
        panel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 240));

        jDesktopPane1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 1060, 520));

        panel4.setBackground(new java.awt.Color(51, 51, 51));
        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 204, 0));
        label1.setText("CAFE MANAGEMENT SYSTEM");
        panel4.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 280, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-restaurant-27.png"))); // NOI18N
        panel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));

        lblDate.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 204, 0));
        lblDate.setText("2022.05.04   23:34:45");
        panel4.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jPanel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 1070, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 1060, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
        jDesktopPane1.removeAll();
        Settings seting = new Settings();
        jDesktopPane1.add(seting).setVisible(true);
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        jDesktopPane1.removeAll();
        DashBoard dash = new DashBoard();
        jDesktopPane1.add(dash).setVisible(true);
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
        jDesktopPane1.removeAll();
        Inventory inven = new Inventory();
        jDesktopPane1.add(inven).setVisible(true);
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        jDesktopPane1.removeAll();
        Menu men = null;
        try {
            men = new Menu();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(men).setVisible(true);
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
        jDesktopPane1.removeAll();
        Report rep = new Report();
        jDesktopPane1.add(rep).setVisible(true);
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel lblDate;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel4;
    private rojerusan.RSButtonHover rSButtonHover2;
    private rojerusan.RSButtonHover rSButtonHover3;
    private rojerusan.RSButtonHover rSButtonHover4;
    private rojerusan.RSButtonHover rSButtonHover5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSPanelCircleImage rSPanelCircleImage1;
    // End of variables declaration//GEN-END:variables
}
