/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Jframes;

import Database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Report extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashBoard
     */
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public Report() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        tableLoard();
        tableLoard1();
    }
    
     
    private void playnotificationMusic() {
    try {
        // Load the audio file
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/Music/Outlook notification sound.wav"));

        // Create a clip to play the audio
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);

        // Play the audio once
        clip.start();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    
    private void tableLoard1(){
       
        try{
        String sql = "SELECT sell_id, no_of_products, total, date FROM sell";
         con = DBConnection.getConnection();
         pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        DefaultTableModel tableModel = resultSetToTableModel(rs);
        tblsell.setModel(tableModel);
        
        // Close the resources
        rs.close();
        pst.close();
       
    } catch (SQLException e) {
        playnotificationMusic();
        JOptionPane.showMessageDialog(this, "Error occurred while loading data: " + e.getMessage());
    }
    }
    
    
     private void tableLoard(){
       
        try{
        String sql = "SELECT product_id, product_name, type, stock, price, status, image, date FROM inventory";
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        DefaultTableModel tableModel = resultSetToTableModel(rs);
        tblItem.setModel(tableModel);
        
        // Close the resources
        rs.close();
        pst.close();
       
    } catch (SQLException e) {
        playnotificationMusic();
        JOptionPane.showMessageDialog(this, "Error occurred while loading data: " + e.getMessage());
    }
    }
    
    private DefaultTableModel resultSetToTableModel(ResultSet rs) throws SQLException {
    ResultSetMetaData metaData = rs.getMetaData();

    // Get column names
    int columnCount = metaData.getColumnCount();
    String[] columnNames = new String[columnCount];
    for (int i = 1; i <= columnCount; i++) {
        columnNames[i - 1] = metaData.getColumnName(i);
    }

    // Get row data
    DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
    while (rs.next()) {
        Object[] rowData = new Object[columnCount];
        for (int i = 1; i <= columnCount; i++) {
            rowData[i - 1] = rs.getObject(i);
        }
        tableModel.addRow(rowData);
    }

    return tableModel;
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsell = new rojerusan.RSTableMetro();
        panel1 = new java.awt.Panel();
        label23 = new java.awt.Label();
        txtProductName = new javax.swing.JTextField();
        rSMaterialButtonRectangle8 = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new rojerusan.RSTableMetro();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblsell.setBackground(new java.awt.Color(51, 51, 51));
        tblsell.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true));
        tblsell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "No of products", "Total", "Date"
            }
        ));
        tblsell.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tblsell.setColorFilasBackgound1(new java.awt.Color(51, 51, 51));
        tblsell.setColorFilasBackgound2(new java.awt.Color(0, 0, 0));
        tblsell.setColorFilasForeground1(new java.awt.Color(255, 204, 0));
        tblsell.setColorFilasForeground2(new java.awt.Color(255, 204, 0));
        tblsell.setColorForegroundHead(new java.awt.Color(255, 204, 0));
        tblsell.setColorSelBackgound(new java.awt.Color(51, 51, 51));
        tblsell.setColorSelForeground(new java.awt.Color(255, 204, 0));
        tblsell.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblsell.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblsell.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblsell.setRowHeight(15);
        jScrollPane2.setViewportView(tblsell);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1010, 160));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1030, 180));

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label23.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        label23.setForeground(new java.awt.Color(255, 204, 0));
        label23.setText("Product Name  :");
        panel1.add(label23, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 240, -1, 40));

        txtProductName.setBackground(new java.awt.Color(102, 102, 102));
        txtProductName.setForeground(new java.awt.Color(255, 204, 0));
        txtProductName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true));
        txtProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductNameKeyReleased(evt);
            }
        });
        panel1.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 220, 40));

        rSMaterialButtonRectangle8.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonRectangle8.setForeground(new java.awt.Color(255, 204, 0));
        rSMaterialButtonRectangle8.setText("Clear");
        rSMaterialButtonRectangle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle8ActionPerformed(evt);
            }
        });
        panel1.add(rSMaterialButtonRectangle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 130, 40));

        tblItem.setBackground(new java.awt.Color(51, 51, 51));
        tblItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true));
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Type", "Stock", "Price", "Status", "Image", "Date"
            }
        ));
        tblItem.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tblItem.setColorFilasBackgound1(new java.awt.Color(0, 0, 0));
        tblItem.setColorFilasBackgound2(new java.awt.Color(51, 51, 51));
        tblItem.setColorFilasForeground1(new java.awt.Color(255, 204, 0));
        tblItem.setColorFilasForeground2(new java.awt.Color(255, 204, 0));
        tblItem.setColorForegroundHead(new java.awt.Color(255, 204, 0));
        tblItem.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tblItem.setColorSelForeground(new java.awt.Color(255, 204, 0));
        tblItem.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblItem.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblItem.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblItem.setRowHeight(15);
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItem);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 1000, 210));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 520));

        setBounds(0, 0, 1070, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void rSMaterialButtonRectangle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle4ActionPerformed

    private void rSMaterialButtonRectangle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle5ActionPerformed

    private void rSMaterialButtonRectangle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle8ActionPerformed
        txtProductName.setText("");
    }//GEN-LAST:event_rSMaterialButtonRectangle8ActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
      
    }//GEN-LAST:event_tblItemMouseClicked

    private void txtProductNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductNameKeyReleased
         String category = txtProductName.getText();
    
    try {
        String sql = "SELECT product_id, product_name, type, stock, price, status, image, date FROM inventory WHERE product_name LIKE ?";
        con = DBConnection.getConnection();
        pst = con.prepareStatement(sql);
        pst.setString(1, "%" + category + "%");
        rs = pst.executeQuery();
        DefaultTableModel tableModel = resultSetToTableModel(rs);
        tblItem.setModel(tableModel);

        // Close the resources
        rs.close();
        pst.close();
       
    } catch (SQLException e) {
        playnotificationMusic();
        JOptionPane.showMessageDialog(this, "Error occurred while loading data: " + e.getMessage());
    }
    }//GEN-LAST:event_txtProductNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label23;
    private java.awt.Panel panel1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle8;
    private rojerusan.RSTableMetro tblItem;
    private rojerusan.RSTableMetro tblsell;
    private javax.swing.JTextField txtProductName;
    // End of variables declaration//GEN-END:variables
}
