/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import Database.DBConnection;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import rojerusan.RSFotoCircle;



/**
 *
 * @author USER
 */
public class signUP extends javax.swing.JFrame {

    /**
     * Creates new form signUP
     */
    
    
    
    String fname;
    String email;
    String uname;
    String password;
    String path =null; 
    
    
    
    public signUP() {
        initComponents();
     
}
    
    
    
    
    
    private void playnotificationMusic() {
    try {
        // Load the audio file
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/Music/Outlook notification sound.wav"));

        // Create a clip to play the audio
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);

        // Play the audio once
        clip.start();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
  
    
    
    private void getData(){
        fname = txtFullName.getText();
        email = txtEmail.getText();
        uname = txtUsername.getText();
        password = txtPassword.getText();
   
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        jPanel1 = new javax.swing.JPanel();
        txtFullName = new rojerusan.RSMetroTextPlaceHolder();
        txtEmail = new rojerusan.RSMetroTextPlaceHolder();
        txtUsername = new rojerusan.RSMetroTextPlaceHolder();
        lblPhoto = new rojerusan.RSFotoCircle();
        label2 = new java.awt.Label();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        txtPassword = new rojerusan.RSMetroTextPlaceHolder();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 206, 1));
        label1.setText("WELCOME BACK");
        panel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Please login here");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("If you already have an account");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-news-125.png"))); // NOI18N
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, 120));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonRectangle3.setForeground(new java.awt.Color(255, 204, 0));
        rSMaterialButtonRectangle3.setText("LOGIN");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });
        panel2.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 170, 40));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 380));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFullName.setBackground(new java.awt.Color(102, 102, 102));
        txtFullName.setForeground(new java.awt.Color(255, 204, 0));
        txtFullName.setBorderColor(new java.awt.Color(255, 204, 0));
        txtFullName.setBotonColor(new java.awt.Color(255, 204, 0));
        txtFullName.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtFullName.setPhColor(new java.awt.Color(255, 204, 0));
        txtFullName.setPlaceholder("Full Name");
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 340, 40));

        txtEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtEmail.setForeground(new java.awt.Color(255, 204, 0));
        txtEmail.setBorderColor(new java.awt.Color(255, 204, 0));
        txtEmail.setBotonColor(new java.awt.Color(255, 204, 0));
        txtEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtEmail.setPhColor(new java.awt.Color(255, 204, 0));
        txtEmail.setPlaceholder("Email");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 340, 40));

        txtUsername.setBackground(new java.awt.Color(102, 102, 102));
        txtUsername.setForeground(new java.awt.Color(255, 204, 0));
        txtUsername.setBorderColor(new java.awt.Color(255, 204, 0));
        txtUsername.setBotonColor(new java.awt.Color(255, 204, 0));
        txtUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtUsername.setPhColor(new java.awt.Color(255, 204, 0));
        txtUsername.setPlaceholder("User Name");
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 340, 40));

        lblPhoto.setBackground(new java.awt.Color(102, 102, 102));
        lblPhoto.setColorBorde(new java.awt.Color(102, 102, 102));
        lblPhoto.setColorBordePopu(new java.awt.Color(255, 204, 0));
        lblPhoto.setColorButtonOptions(new java.awt.Color(255, 204, 0));
        lblPhoto.setColorButtonOptionsHover(new java.awt.Color(255, 204, 0));
        lblPhoto.setColorFondo(new java.awt.Color(255, 204, 0));
        lblPhoto.setColorTextButtonsPopu(new java.awt.Color(102, 102, 102));
        lblPhoto.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-contacts-125 (1).png"))); // NOI18N
        jPanel1.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 110, 120));

        label2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 206, 1));
        label2.setText("SIGNUP");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonRectangle2.setForeground(new java.awt.Color(255, 204, 0));
        rSMaterialButtonRectangle2.setText("SIGNUP");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 170, 40));

        txtPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtPassword.setForeground(new java.awt.Color(255, 204, 0));
        txtPassword.setBorderColor(new java.awt.Color(255, 204, 0));
        txtPassword.setBotonColor(new java.awt.Color(255, 204, 0));
        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtPassword.setPhColor(new java.awt.Color(255, 204, 0));
        txtPassword.setPlaceholder("Password");
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 340, 40));

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 600, 380));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
         getData();
    
    // Check if all text fields are filled
    if (fname.isEmpty() || email.isEmpty() || uname.isEmpty() || password.isEmpty()) {
        playnotificationMusic();
        JOptionPane.showMessageDialog(this, "<html><body><h2>Error!</h2>"
            + "<p>All fields are required.</p></body></html>", "Registration Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        String sql = "INSERT INTO signup (full_name, email, username, password, image) VALUES (?, ?, ?, ?, ?)";
        Connection con;
        PreparedStatement pst = null;

        try {
            con = DBConnection.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, fname);
            pst.setString(2, email);
            pst.setString(3, uname);
            pst.setString(4, password);

            path= lblPhoto.getRutaImagen();

            InputStream is = new FileInputStream(new File(path));
            pst.setBlob(5, is);

            pst.executeUpdate();

            String message = "<html><body><h2>Successfully Registered!</h2>"
                    + "<p>Now you can log in with your username: <strong>" + uname + "</strong></p>"
                    + "<p>Password: <strong>" + password + "</strong></p></body></html>";
            playnotificationMusic();
            JOptionPane.showMessageDialog(this, message, "Registration Successful", JOptionPane.INFORMATION_MESSAGE);

            txtEmail.setText("");
            txtFullName.setText("");
            txtPassword.setText("");
            txtUsername.setText("");
            String imagePath = "C:\\Users\\USER\\Documents\\NetBeansProjects\\Cafe Management System\\src\\Images\\icons8-contacts-125 (1).png";
            ImageIcon defaultIcon = new ImageIcon(imagePath);
            lblPhoto.setImagenDefault(defaultIcon);

        } catch (SQLException | FileNotFoundException ex) {
            playnotificationMusic();
            JOptionPane.showMessageDialog(this, "<html><body><h2>Error!</h2>"
                + "<p>An error occurred while registering:</p>"
                + "<p>" + ex.getMessage() + "</p></body></html>", "Registration Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        playnotificationMusic();
        JOptionPane.showMessageDialog(this, "<html><body><h2>Error!</h2>"
            + "<p>An error occurred while registering:</p>"
            + "<p>" + e.getMessage() + "</p></body></html>", "Registration Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private rojerusan.RSFotoCircle lblPhoto;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMetroTextPlaceHolder txtEmail;
    private rojerusan.RSMetroTextPlaceHolder txtFullName;
    private rojerusan.RSMetroTextPlaceHolder txtPassword;
    private rojerusan.RSMetroTextPlaceHolder txtUsername;
    // End of variables declaration//GEN-END:variables
}
