/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author USER
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),40,40));
        
        
        
        Timer timer = new Timer(1000, new ActionListener() {
    boolean isVisible = true;

    @Override
    public void actionPerformed(ActionEvent e) {
        // Toggle the visibility of the label
        lblshehanz.setVisible(isVisible);
        isVisible = !isVisible;
    }
});

// Start the Timer
timer.start();
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        circleProgressBar1 = new Database.CircleProgressBar();
        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        circleProgressBar2 = new Database.CircleProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblshehanz = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblLoadingvalue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circleProgressBar2.setBackground(new java.awt.Color(0, 0, 0));
        circleProgressBar2.setForeground(new java.awt.Color(255, 204, 0));
        jPanel1.add(circleProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 240, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("CAFE MANAGEMENT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Version - 1.0");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 80, 110, -1));

        lblshehanz.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblshehanz.setForeground(new java.awt.Color(255, 204, 0));
        lblshehanz.setText("ShehanZ Tech");
        jPanel1.add(lblshehanz, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, 30));

        lblLoading.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(255, 204, 0));
        lblLoading.setText("Loading....");
        jPanel1.add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 210, -1));

        lblLoadingvalue.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblLoadingvalue.setForeground(new java.awt.Color(255, 204, 0));
        lblLoadingvalue.setText("0%");
        jPanel1.add(lblLoadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-bakery-shop-100.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, 130));

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 690, 440));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }

            
       Splash sp = new Splash();
       sp.setVisible(true);
       Login l = new  Login();
               
       
       try{
           
           for(int i = 0; i<=100;i++){
               Thread.sleep(100);
               sp.lblLoadingvalue.setText(i+"%");
               
               if(i==10){
                   sp.lblLoading.setText("Turning on Modules...");
        /*lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);*/
               }
               if(i==20){
                   sp.lblLoading.setText("Loading on Modules...");
                   
               }
               if(i==50){
                   sp.lblLoading.setText("Connecting to Database...");
                   
               }
               if(i==70){
                   sp.lblLoading.setText("Connection Successful !");
                   
               }
               if(i==80){
                   sp.lblLoading.setText("Launching Application...");
                   
               }
             
               sp.circleProgressBar2.setValue(i);
               
           }
           
       }
       catch(Exception ex){
           ex.printStackTrace();
       }
       
       sp.setVisible(false);
       l.setVisible(true);
       
       sp.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Database.CircleProgressBar circleProgressBar1;
    private Database.CircleProgressBar circleProgressBar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoadingvalue;
    private javax.swing.JLabel lblshehanz;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
